name: please-go-home-cron
on:
  schedule:
    - cron: '30-59 7 * * 1-5'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://playground-nextjs-osori.vercel.app/api/map/gohome?start=126.77801150878531,37.658031591237425&goal=126.82325269403174,37.55138140215686'
